export default Object.freeze({
  FETCH_TOTALS_START: "FETCH_TOTALS_START",
  FETCH_TOTALS_SUCCESS: "FETCH_TOTALS_SUCCESS",
  FETCH_TOTALS_FAILED: "FETCH_TOTALS_FAILED",

  TOTAL_VIRTUAL_CARD_TRANSACTIONS_START:
    "TOTAL_VIRTUAL_CARD_TRANSACTIONS_START",
  TOTAL_VIRTUAL_CARD_TRANSACTIONS_SUCCESS:
    "TOTAL_VIRTUAL_CARD_TRANSACTIONS_SUCCESS",
  TOTAL_VIRTUAL_CARD_TRANSACTIONS_FAILED:
    "TOTAL_VIRTUAL_CARD_TRANSACTIONS_FAILED",

  GLOBALGENG_CARD_START: "GLOBALGENG_CARD_START",
  GLOBALGENG_CARD_SUCCESS: "GLOBALGENG_CARD_SUCCESS",
  GLOBALGENG_CARD_FAILED: "GLOBALGENG_CARD_FAILED",

  GET_CONNECTED_ACCOUNT_START: "GET_CONNECTED_ACCOUNT_START",
  GET_CONNECTED_ACCOUNT_SUCCESS: "GET_CONNECTED_ACCOUNT_SUCCESS",
  GET_CONNECTED_ACCOUNT_FAILED: "GET_CONNECTED_ACCOUNT_FAILED",

  VIRTUAL_CARD_WAITLIST_START: "VIRTUAL_CARD_WAITLIST_START",
  VIRTUAL_CARD_WAITLIST_SUCCESS: "VIRTUAL_CARD_WAITLIST_SUCCESS",
  VIRTUAL_CARD_WAITLIST_FAILED: "VIRTUAL_CARD_WAITLIST_FAILED",

  GET_TRANSACTIONS_START: "GET_TRANSACTIONS_START",
  GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
  GET_TRANSACTIONS_FAILED: "GET_TRANSACTIONS_FAILED",

  GET_BILLS_TRANSACTIONS_START: "GET_BILLS_TRANSACTIONS_START",
  GET_BILLS_TRANSACTIONS_SUCCESS: "GET_BILLS_TRANSACTIONS_SUCCESS",
  GET_BILLS_TRANSACTIONS_FAILED: "GET_BILLS_TRANSACTIONS_FAILED",

  CARD_TRANSACTIONS_START: "CARD_TRANSACTIONS_START",
  CARD_TRANSACTIONS_SUCCESS: "CARD_TRANSACTIONS_SUCCESS",
  CARD_TRANSACTIONS_FAILED: "CARD_TRANSACTIONS_FAILED",

  FOUNDERS_CARD_TRANSACTIONS_START: "FOUNDERS_CARD_TRANSACTIONS_START",
  FOUNDERS_CARD_TRANSACTIONS_SUCCESS: "FOUNDERS_CARD_TRANSACTIONS_SUCCESS",
  FOUNDERS_CARD_TRANSACTIONS_FAILED: "FOUNDERS_CARD_TRANSACTIONS_FAILED",

  FOUNDERS_CARD_USERS_START: "FOUNDERS_CARD_USERS_START",
  FOUNDERS_CARD_USERS_SUCCESS: "FOUNDERS_CARD_USERS_SUCCESS",
  FOUNDERS_CARD_USERS_FAILED: "FOUNDERS_CARD_USERS_FAILED",

  SEARCH_CARD_TRANSACTION_START: "SEARCH_CARD_TRANSACTION_START",
  SEARCH_CARD_TRANSACTION_SUCCESS: "SEARCH_CARD_TRANSACTION_SUCCESS",
  SEARCH_CARD_TRANSACTION_FAILED: "SEARCH_CARD_TRANSACTION_FAILED",

  FETCH_ALL_PENDING_ACCT_REQ_START: "FETCH_ALL_PENDING_ACCT_REQ_START",
  FETCH_ALL_PENDING_ACCT_REQ_SUCCESS: "FETCH_ALL_PENDING_ACCT_REQ_SUCCESS",
  FETCH_ALL_PENDING_ACCT_REQ_FAILED: "FETCH_ALL_PENDING_ACCT_REQ_FAILED",


  FETCH_ALL_PETITION_REQ_START: "FETCH_ALL_PETITION_REQ_START",
  FETCH_ALL_PETITION_REQ_SUCCESS: "FETCH_ALL_PETITION_REQ_SUCCESS",
  FETCH_ALL_PETITION_REQ_FAILED: "FETCH_ALL_PETITION_REQ_FAILED",


  FETCH_ALL_STV_REQ_START: "FETCH_ALL_STV_REQ_START",
  FETCH_ALL_STV_REQ_SUCCESS: "FETCH_ALL_STV_REQ_SUCCESS",
  FETCH_ALL_STV_REQ_FAILED: "FETCH_ALL_STV_REQ_FAILED",

  FETCH_ALL_WITHDRWL_REQ_START: "FETCH_ALL_WITHDRWL_REQ_START",
  FETCH_ALL_WITHDRWL_REQ_SUCCESS: "FETCH_ALL_WITHDRWL_REQ_SUCCESS",
  FETCH_ALL_WITHDRWL_REQ_FAILED: "FETCH_ALL_WITHDRWL_REQ_FAILED",

  FETCH_COUNTRIES_START: "FETCH_COUNTRIES_START",
  FETCH_COUNTRIES_SUCCESS: "FETCH_COUNTRIES_SUCCESS",
  FETCH_COUNTRIES_FAILED: "FETCH_COUNTRIES_FAILED",
});
