export default Object.freeze({
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILED: "LOGIN_USER_FAILED",


  PASSWORD_UPDATE_START: "PASSWORD_UPDATE_START",
  PASSWORD_UPDATE_SUCCESS: "PASSWORD_UPDATE_SUCCESS",
  PASSWORD_UPDATE_FAILED: "PASSWORD_UPDATE_FAILED",

  OTP_VERIFICATION_START: "OTP_VERIFICATION_START",
  OTP_VERIFICATION_SUCCESS: "OTP_VERIFICATION_SUCCESS",
  OTP_VERIFICATION_FAILED: "OTP_VERIFICATION_FAILED",

  LOAD_USER_DATA: "LOAD_USER_DATA",
  LOGOUT_USER: "LOGOUT_USER",

  MODAL_OPEN: "MODAL_OPEN",
  MODAL_CLOSE: "MODAL_CLOSE",
});
