export default Object.freeze({
  FETCH_USERS_START: "FETCH_USERS_START",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILED: "FETCH_USERS_FAILED",

  FETCH_USER_START: "FETCH_USER_START",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILED: "FETCH_USER_FAILED",
  
  FETCH_USER_TRANSACTIONS_START: "FETCH_USER_TRANSACTIONS_START",
  FETCH_USER_TRANSACTIONS_SUCCESS: "FETCH_USER_TRANSACTIONS_SUCCESS",
  FETCH_USER_TRANSACTIONS_FAILED: "FETCH_USER_TRANSACTIONS_FAILED",

  SEARCH_USER_START: "SEARCH_USER_START",
  SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
  SEARCH_USER_FAILED: "SEARCH_USER_FAILED",

  SHOW_MODAL : "SHOW_MODAL"
});
